#!/usr/bin/env python3
"""
Compute SHA-256 checksums for the deposited archives and rewrite
data/raw/MANIFEST.md with the real sizes and hashes.

    python scripts/make_manifest.py path/to/Scalability_Simulation_N1-N5.zip \
                                    path/to/DigitalTwin_Scenes.zip

Any number of files may be passed; each is hashed and added to the table.
Files already listed in the manifest are updated in place, so the script is safe
to re-run after replacing an archive.

Large files are read in chunks, so hashing a multi-gigabyte archive uses a
constant amount of memory.  Expect roughly a minute per gigabyte on a
conventional disk.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from datetime import date
from pathlib import Path

CHUNK = 1 << 20  # 1 MiB

TABLE_START = "<!-- CHECKSUM TABLE START -->"
TABLE_END = "<!-- CHECKSUM TABLE END -->"


def sha256(path: Path, quiet: bool = False) -> str:
    h = hashlib.sha256()
    total = path.stat().st_size
    done = 0
    with path.open("rb") as fh:
        while chunk := fh.read(CHUNK):
            h.update(chunk)
            done += len(chunk)
            if not quiet and total > 50 * CHUNK:
                pct = 100 * done / total
                print(f"\r  {path.name}: {pct:5.1f} %", end="", flush=True)
    if not quiet and total > 50 * CHUNK:
        print(f"\r  {path.name}: done      ")
    return h.hexdigest()


def human_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return f"{n:.1f} {unit}" if unit != "B" else f"{n} B"
        n /= 1024.0
    return f"{n:.1f} TB"


def parse_existing(text: str) -> dict[str, tuple[str, str]]:
    """Recover rows already present, so re-runs update rather than replace."""
    rows: dict[str, tuple[str, str]] = {}
    m = re.search(f"{TABLE_START}(.*?){TABLE_END}", text, re.S)
    if not m:
        return rows
    for line in m.group(1).splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 3 and cells[0].startswith("`"):
            rows[cells[0].strip("`")] = (cells[1], cells[2])
    return rows


def render_table(rows: dict[str, tuple[str, str]]) -> str:
    lines = [TABLE_START,
             "",
             "| File | Size | SHA-256 |",
             "|---|---|---|"]
    for name, (size, digest) in sorted(rows.items()):
        lines.append(f"| `{name}` | {size} | `{digest}` |")
    lines += ["",
              f"_Generated by `scripts/make_manifest.py` on "
              f"{date.today().isoformat()}._",
              "",
              TABLE_END]
    return "\n".join(lines)


def main(paths: list[Path], manifest: Path) -> int:
    missing = [p for p in paths if not p.is_file()]
    if missing:
        for p in missing:
            print(f"error: not found: {p}", file=sys.stderr)
        return 1

    text = manifest.read_text(encoding="utf-8")
    rows = parse_existing(text)

    print(f"hashing {len(paths)} file(s):")
    for p in paths:
        digest = sha256(p)
        rows[p.name] = (human_size(p.stat().st_size), digest)
        print(f"  {p.name}  {human_size(p.stat().st_size)}  {digest}")

    if TABLE_START in text:
        new = re.sub(f"{re.escape(TABLE_START)}.*?{re.escape(TABLE_END)}",
                     lambda _: render_table(rows), text, flags=re.S)
    else:
        new = text.rstrip() + "\n\n" + render_table(rows) + "\n"

    manifest.write_text(new, encoding="utf-8")
    print(f"\nupdated {manifest}")
    print("commit it, then upload the archives to Figshare.")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+", type=Path)
    ap.add_argument("--manifest", type=Path,
                    default=Path("data/raw/MANIFEST.md"))
    a = ap.parse_args()
    raise SystemExit(main(a.files, a.manifest))
